---
version: '2'

services:

  semantic-triplifier:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pdnd-semantic-triplifier
    image: teamdigitale/pdnd-semantic-triplifier
    stdin_open: true
    tty: true
    ports:
      - 7777:7777/tcp
